---
version: 3
images:
  base_image:
    name: BASE_IMAGE_PH

dependencies:
  galaxy: collections/requirements.yml
  python: python-requirements.txt
  exclude:
    system:
      - openshift-clients
    all_from_collections:
      - amazon.aws

additional_build_steps:  
  prepend_final:
    - "RUN curl -LO https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/stable/openshift-client-linux-amd64-rhel8.tar.gz && tar -C /usr/local/bin -xf openshift-client-linux-amd64-rhel8.tar.gz && rm -f openshift-client-linux-amd64-rhel8.tar.gz"
    - "RUN curl -LO https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/stable/ccoctl-linux-rhel8.tar.gz && tar -C /usr/local/bin -xf ccoctl-linux-rhel8.tar.gz && rm -f ccoctl-linux-rhel8.tar.gz"
    - "RUN curl -LO 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' && unzip awscli-exe-linux-x86_64.zip && ./aws/install && rm -rf aws && rm awscli-exe-linux-x86_64.zip"

options:
  package_manager_path: /usr/bin/microdnf
