---
version: 3
images:
  base_image:
    name: BASE_IMAGE_PH

dependencies:
  galaxy: collections/requirements.yml
  python: python-requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
