apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pah-login-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: pah-login-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: aap-ci-pah-login
