---
version: 3
images:
  base_image:
    name: BASE_IMAGE_PH

dependencies:
  galaxy: collections/requirements.yml
  exclude:
    all_from_collections:
      - arista.eos
      - vyos.vyos

options:
  package_manager_path: /usr/bin/microdnf
