---
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  galaxy: collections/requirements.yml
  python: python-requirements.txt

additional_build_files:
  - src: files
    dest: resources

additional_build_steps:
  prepend_galaxy:
    - COPY _build/resources/ansible.cfg /etc/ansible/ansible.cfg
  prepend_final:
    - COPY _build/resources/signal9-ca.crt /etc/pki/ca-trust/source/anchors/signal9-ca.crt
    - RUN /bin/update-ca-trust

options:
  package_manager_path: /usr/bin/microdnf
